-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Autor: Tiago Arruda Ferreira

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_RU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_RU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_RU` DEFAULT CHARACTER SET utf8 ;
USE `DB_RU` ;

-- -----------------------------------------------------
-- Table `DB_RU`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`Pessoa` (
  `cpf` INT UNSIGNED NOT NULL,
  `digital` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `digital`),
  UNIQUE INDEX `pessoa_Id_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `digital_UNIQUE` (`digital` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`administrador` (
  `registro_adm` INT NOT NULL,
  `Pessoa_cpf` INT UNSIGNED NOT NULL,
  `Pessoa_digital` INT NULL,
  PRIMARY KEY (`registro_adm`, `Pessoa_cpf`, `Pessoa_digital`),
  INDEX `fk_administrador_Pessoa1_idx` (`Pessoa_cpf` ASC, `Pessoa_digital` ASC),
  CONSTRAINT `fk_administrador_Pessoa1`
    FOREIGN KEY (`Pessoa_cpf` , `Pessoa_digital`)
    REFERENCES `DB_RU`.`Pessoa` (`cpf` , `digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`usuario` (
  `categoria` INT NOT NULL,
  `Pessoa_cpf` INT UNSIGNED NOT NULL,
  `Pessoa_digital` INT NULL,
  PRIMARY KEY (`categoria`, `Pessoa_cpf`, `Pessoa_digital`),
  INDEX `fk_usuario_Pessoa1_idx` (`Pessoa_digital` ASC),
  CONSTRAINT `fk_usuario_Pessoa1`
    FOREIGN KEY (`Pessoa_digital`)
    REFERENCES `DB_RU`.`Pessoa` (`digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`aluno` (
  `rga` INT NOT NULL,
  `curso` VARCHAR(45) NULL,
  `staus` VARCHAR(8) NOT NULL,
  `limitemax` DECIMAL(5,2) NULL,
  `usuario_categoria` INT NOT NULL,
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  `usuario_Pessoa_digital` INT NULL,
  PRIMARY KEY (`rga`, `usuario_categoria`, `usuario_Pessoa_cpf`, `usuario_Pessoa_digital`),
  UNIQUE INDEX `rga_UNIQUE` (`rga` ASC),
  INDEX `fk_aluno_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC, `usuario_Pessoa_digital` ASC),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf` , `usuario_Pessoa_digital`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf` , `Pessoa_digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`servidor` (
  `registro_sev` INT NOT NULL,
  `funcao` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `limitemax` DECIMAL(5,2) NOT NULL,
  `usuario_categoria` INT NOT NULL,
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  `usuario_Pessoa_digital` INT NULL,
  PRIMARY KEY (`registro_sev`, `usuario_categoria`, `usuario_Pessoa_cpf`, `usuario_Pessoa_digital`),
  UNIQUE INDEX `registro_sev_UNIQUE` (`registro_sev` ASC),
  INDEX `fk_servidor_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC, `usuario_Pessoa_digital` ASC),
  CONSTRAINT `fk_servidor_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf` , `usuario_Pessoa_digital`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf` , `Pessoa_digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`visitante` (
  `visitante_id` INT NOT NULL AUTO_INCREMENT,
  `limitemax` DECIMAL(5,2) NULL,
  `usuario_categoria` INT NOT NULL,
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  `usuario_Pessoa_digital` INT NULL,
  PRIMARY KEY (`visitante_id`, `usuario_categoria`, `usuario_Pessoa_cpf`, `usuario_Pessoa_digital`),
  UNIQUE INDEX `idvisitante_UNIQUE` (`visitante_id` ASC),
  INDEX `fk_visitante_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC, `usuario_Pessoa_digital` ASC),
  CONSTRAINT `fk_visitante_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf` , `usuario_Pessoa_digital`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf` , `Pessoa_digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`saldo` (
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  `usuario_categoria` INT NOT NULL,
  `quantidade` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`usuario_Pessoa_cpf`, `usuario_categoria`),
  INDEX `fk_saldo_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC),
  CONSTRAINT `fk_saldo_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`avaliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`avaliar` (
  `avaliar_Id` INT NOT NULL,
  `Pessoa_cpf` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`avaliar_Id`, `Pessoa_cpf`),
  INDEX `fk_avaliar_Pessoa1_idx` (`Pessoa_cpf` ASC),
  CONSTRAINT `fk_avaliar_Pessoa1`
    FOREIGN KEY (`Pessoa_cpf`)
    REFERENCES `DB_RU`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`venda` (
  `numero_ven` INT NOT NULL AUTO_INCREMENT,
  `valor_compra` DECIMAL(5,2) NULL,
  `data_ven` DATE NULL,
  `usuario_categoria` INT NOT NULL,
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_ven`, `usuario_categoria`, `usuario_Pessoa_cpf`),
  UNIQUE INDEX `numero_ven_UNIQUE` (`numero_ven` ASC),
  INDEX `fk_venda_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC),
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`categoria_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`categoria_movimento` (
  `horario_in` INT NULL,
  `categoria_id` INT NOT NULL,
  `name_categoria` VARCHAR(20) NOT NULL,
  `horario_fim` INT NULL,
  `valor_mov` DECIMAL(5,2) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`movimento` (
  `numero _mov` INT NOT NULL AUTO_INCREMENT,
  `data_mov` DATE NULL,
  `quantidade_refeicao` INT NULL,
  `quantidade_momento` INT NULL,
  `categoria_movimento_categoria_id` INT NOT NULL,
  PRIMARY KEY (`numero _mov`, `categoria_movimento_categoria_id`),
  UNIQUE INDEX `numero _mov_UNIQUE` (`numero _mov` ASC),
  INDEX `fk_movimento_categoria_movimento1_idx` (`categoria_movimento_categoria_id` ASC),
  CONSTRAINT `fk_movimento_categoria_movimento1`
    FOREIGN KEY (`categoria_movimento_categoria_id`)
    REFERENCES `DB_RU`.`categoria_movimento` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`cardapio` (
  `cardapio_Id` INT NOT NULL AUTO_INCREMENT,
  `data_cardapio` DATETIME NOT NULL,
  `descriçao` VARCHAR(45) NULL,
  PRIMARY KEY (`cardapio_Id`),
  UNIQUE INDEX `cardapio_Id_UNIQUE` (`cardapio_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`adminstrador_atualiza_cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`adminstrador_atualiza_cardapio` (
  `cardapio_cardapio_Id` INT NOT NULL,
  `administrador_registro_adm` INT NOT NULL,
  `Data` DATETIME NOT NULL,
  PRIMARY KEY (`cardapio_cardapio_Id`, `administrador_registro_adm`),
  INDEX `fk_adminstrador_atualiza_cardapio_cardapio1_idx` (`cardapio_cardapio_Id` ASC),
  INDEX `fk_adminstrador_atualiza_cardapio_administrador1_idx` (`administrador_registro_adm` ASC),
  CONSTRAINT `fk_adminstrador_atualiza_cardapio_cardapio1`
    FOREIGN KEY (`cardapio_cardapio_Id`)
    REFERENCES `DB_RU`.`cardapio` (`cardapio_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adminstrador_atualiza_cardapio_administrador1`
    FOREIGN KEY (`administrador_registro_adm`)
    REFERENCES `DB_RU`.`administrador` (`registro_adm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_RU`.`usuario_acessa_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_RU`.`usuario_acessa_movimento` (
  `movimento_numero _mov` INT NOT NULL,
  `movimento_categoria_movimento_categoria_id` INT NOT NULL,
  `usuario_categoria` INT NOT NULL,
  `usuario_Pessoa_cpf` INT UNSIGNED NOT NULL,
  `usuario_Pessoa_digital` INT NOT NULL,
  `data_acesso` DATETIME NULL,
  PRIMARY KEY (`movimento_numero _mov`, `movimento_categoria_movimento_categoria_id`, `usuario_categoria`, `usuario_Pessoa_cpf`, `usuario_Pessoa_digital`),
  INDEX `fk_usuario_acessa_movimento_movimento1_idx` (`movimento_numero _mov` ASC, `movimento_categoria_movimento_categoria_id` ASC),
  INDEX `fk_usuario_acessa_movimento_usuario1_idx` (`usuario_categoria` ASC, `usuario_Pessoa_cpf` ASC, `usuario_Pessoa_digital` ASC),
  CONSTRAINT `fk_usuario_acessa_movimento_movimento1`
    FOREIGN KEY (`movimento_numero _mov` , `movimento_categoria_movimento_categoria_id`)
    REFERENCES `DB_RU`.`movimento` (`numero _mov` , `categoria_movimento_categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_acessa_movimento_usuario1`
    FOREIGN KEY (`usuario_categoria` , `usuario_Pessoa_cpf` , `usuario_Pessoa_digital`)
    REFERENCES `DB_RU`.`usuario` (`categoria` , `Pessoa_cpf` , `Pessoa_digital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
